### ISSUE TITLE
In version 1.0.5 I cannot create more than 29 groups

### ISSUE THREAD

**Issue by gaperez64** [usvn/usvn#36]
So the problem I have is that I have now created 30 users with a group each. Every user has a project and some files. Now, if a user goes to the web interface and tries to change the rights to some file he will lose all information on the rights to that folder. That is, if I initially had rights for text.txt and now add the rights to read/write to a second user then everyone loses the rights to this file.

I have verified that the ajax function does indeed send the information of the checkboxes to the webservice (BrowserajaxController). However, if you print $_GET['rights'] in the function that implements the service you get an error that says the key is not found (so it does not find the parameter rights). This is despite the fact that apache reports the correct query having been received. I suppose there is some problem in the routing or some preDispatch call I am not seeing (not a Zend expert here) but this is driving me crazy.

Any ideas are welcome :)

**Comment by mckaygerhard** [comment]
i have 28 groups with 12 users, seems the problems its how the browsers are manage the calls.. 

i used iceweasel and no problems.. of course i use linux older, do you try a more older browser?
