### ISSUE TITLE
500err in 1.0.7,when upgrade subversion from 1.6 to 1.9

### ISSUE THREAD

**Issue by xiagw** [usvn/usvn#51]
When upgrade subversion from 1.6 to 1.9, can't commit to server. 500error.

192.168.6.2 - 1005 [06/May/2017:20:15:03 +0800] "POST /usvn/svn/sandbox/!svn/me HTTP/1.1" 500 516 "-" "SVN/1.9.5 (x86_64-redhat-linux-gnu) serf/1.3.7"

**Comment by xiagw** [comment]
someone help me ?

**Comment by mckaygerhard** [comment]
if everything its working dont upgrade!

the stupid subversion team changes a lot of commands behavior, the problem its the subversion behavior

check this list of changes and then apply to your "win"-hat: 

1. the 1.6 to 1.7/1.8 upgrade related: http://subversion.apache.org/docs/release-notes/1.8.html#issues
2. all of that must be merged with: http://subversion.apache.org/docs/release-notes/1.9#issues
3. and of course the most common: http://qgqlochekone.blogspot.com/2017/03/gambasrapidsvnsubversion-avoit-413.html

**Comment by jackeri0** [comment]
I resovled this issue by adding `RewriteRule ^svn/ - [L,NC]` to the file `public/.htaccess`.

**Comment by jackeri0** [comment]
@xiagw I resolved this problem by adding `RewriteRule ^svn/ - [L,NC]` to the file `public/.htaccess`:
```
<Files *.ini>
Require all denied
</Files>

php_flag short_open_tag on
php_flag magic_quotes_gpc off

RewriteEngine on
#RewriteCond
RewriteBase "//usvn/"
RewriteRule ^svn/ - [L,NC]       #add to here
RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -l [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^.*$ - [NC,L]
RewriteRule ^.*$ index.php [NC,L]

**Comment by mckaygerhard** [comment]
good to know.. maybe now someone close this issue .. but today apache2 are not so used!

**Comment by Akumotor** [comment]
@jackeri0 Thank you ever so much， it works for me too!
