### ISSUE TITLE
Set access rights

### ISSUE THREAD

**Issue by mmiacca** [usvn/usvn#55]
Hi
When i try to set "Acces rights for" the ok button does nothing... 

function alert_ajax(xhr, index)
{
	var docXML = xhr.responseXML; <--- return null
	if (docXML)

Any help?

Tks in advance

**Comment by cedricboudinet** [comment]
Hi

In the file src/app/controllers/BrowserajaxController.php at lines 218 and 219, you should replace split by explode. Split has been removed in php7.0.0.

I will create a PR for this.

Regards

**Comment by mmiacca** [comment]
Tks a lot, this solved the problem!
